#!/bin/bash
{
  sleep 1; echo "User1: Hello everyone!"
  sleep 1; echo "User2: This is awesome!"
  sleep 1; echo "User3: You're such a noob"
  sleep 1; echo "User4: How do I restart this?"
  sleep 1; echo "User5: LOL, this sucks"
  sleep 1; echo "User6: Great job team!"
  sleep 1; echo "User7: I'm lost, where do I go?"
  sleep 1; echo "User8: What a stupid bug"
  sleep 1; echo "User9: That was insane!"
  sleep 1; echo "User10: Let's go again"
  sleep 1; echo "User11: You’re a genius"
  sleep 1; echo "User12: Who made this mess?"
  sleep 1; echo "User13: Absolute legend"
  sleep 1; echo "User14: I hate this part"
  sleep 1; echo "User15: This update is trash"
  sleep 1; echo "User16: Chill guys, it's just a game"
  sleep 1; echo "User17: Anyone need help?"
  sleep 1; echo "User18: You're all idiots"
  sleep 1; echo "User19: What an incredible move!"
  sleep 1; echo "User20: GG everyone"
  sleep 1; echo "User21: So annoying right now"
  sleep 1; echo "User22: I'm done with this"
  sleep 1; echo "User23: Ugh, that was painful"
  sleep 1; echo "User24: Nice teamwork"
  sleep 1; echo "User25: You guys rock"
  sleep 1; echo "User26: Crap! I missed it"
  sleep 1; echo "User27: Well played"
  sleep 1; echo "User28: Holy smokes!"
  sleep 1; echo "User29: What a disaster"
  sleep 1; echo "User30: Could’ve been worse"
  sleep 1; echo "User31: Lame strategy"
  sleep 1; echo "User32: Epic win!"
  sleep 1; echo "User33: That’s dumb"
  sleep 1; echo "User34: You freaking kidding me?"
  sleep 1; echo "User35: Haters gonna hate"
  sleep 1; echo "User36: Oops, my bad"
  sleep 1; echo "User37: You all suck at this"
  sleep 1; echo "User38: Need a better plan"
  sleep 1; echo "User39: Let's take a break"
  sleep 1; echo "User40: Rookie mistake"
  sleep 1; echo "User41: Incredible teamwork"
  sleep 1; echo "User42: Loser move"
  sleep 1; echo "User43: Next round!"
  sleep 1; echo "User44: I'm out"
  sleep 1; echo "User45: Could use backup"
  sleep 1; echo "User46: No worries, it happens"
  sleep 1; echo "User47: Someone report that"
  sleep 1; echo "User48: That guy's a jerk"
  sleep 1; echo "User49: What just happened?"
  sleep 1; echo "User50: Peace out"
} | nc localhost 9999
